# Generated by Django 3.2.7 on 2021-09-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Welcome to my Page', max_length=255),
        ),
    ]
